### ISSUE TITLE
時刻入力方式をXXXXに対応させる

### ISSUE THREAD

**Issue by hemipogo** [odpt2018/sapj-opd-trainschedulebot-recast#14]
18時50分、ではなく1850で入力してもらえるよう文言を修正。
（Requirementsから直接編集しちゃってください）

**Comment by Miwako1127** [comment]
「何時頃の電車ですかよ？　4桁の数字で入力してくれよな！
例えば、午前9時ちょうどなら0900、午後9時5分なら2105だぜ！」
ってしました。

**Comment by hemipogo** [comment]
ありがとうございました！
