### ISSUE TITLE
新スキル「使い方」作成

### ISSUE THREAD

**Issue by hemipogo** [odpt2018/sapj-opd-trainschedulebot-recast#20]
使い方について知りたいときに教えてくれる機能。
親しみやすい口調で、大体以下の内容がわかるようにしたいです。

・メトロにしか対応していない
・「路線」「出発駅」「到着駅」「出発時刻」「平日/休日」入力するとそこから1時間もしくは10本の時刻表を教えてくれる
・1文検索ができる
・ひらがな検索ができる
・まちがえたら最初からやり直しが必要
・やり直しコマンド例

**Comment by sasakimo** [comment]
教えて/初めて/使い方/どうやる/わかんない　などのWordで、使い方を返すようになってます

**Comment by hemipogo** [comment]
素敵です！！
