### ISSUE TITLE
口調・語尾を変更する

### ISSUE THREAD

**Issue by hemipogo** [odpt2018/sapj-opd-trainschedulebot-recast#23]
女子、いぬ、武士など、調べる太郎くんのキャラクターを増やす。
スキルまるまるコピーOR今のスキルのIF文で分岐とかで実装できるかも…？

**Comment by Miwako1127** [comment]
女子とか入れると、スキルが発動して女子言葉になるようにしました。
全体ができあがったら、最後に微調整いれるかもしれませんが、一応終了です。

**Comment by 0ta** [comment]
女子っていれてみましたが変化無しです。何かこつがありますか？
