### ISSUE TITLE
駅名をGAZETTEでシノニム登録

### ISSUE THREAD

**Issue by hemipogo** [odpt2018/sapj-opd-trainschedulebot-recast#4]
半蔵門、半蔵門駅、のパターンでそれぞれSTATIONのガゼットに登録する。
オープンデータからAPIでCSVに変換する作業が必要らしいのですが
やり方はどうやら米原さんが詳しいようなので一緒にやれると良いかもです。
駅はあんまり増えたり減ったりしないのですべての駅でできるとかっこいいです。

**Comment by yynhr** [comment]
駅名のGAZETTEはこれ見てやってみてください
https://sap-dbs-japan.slack.com/archives/CBV4GT8D7/p1539875047000100

**Comment by sasakimo** [comment]
見ましたーやてみます

**Comment by sasakimo** [comment]
引き続きcsvでUploadできないんですけど、ちょびちょび手作業でやってますー

**Comment by sasakimo** [comment]
終わりましたー

**Comment by hemipogo** [comment]
Macからシノニム一括登録できましたが、そうすると一文検索が怪しくなるという現象に見舞われたため、有効化については蔡本さんテスト後に再確認します。
