### ISSUE TITLE
路線名をGAZETTEでシノニム登録 <TO BE ASSIGNED to YNP>

### ISSUE THREAD

**Issue by hemipogo** [odpt2018/sapj-opd-trainschedulebot-recast#5]
半蔵門線、のパターンでそれぞれSTATIONのガゼットに登録する。
オープンデータからAPIでCSVに変換する作業が必要らしいのですが
やり方はどうやら米原さんが詳しいようなので一緒にやれると良いかもです。
 駅名（漢字）のGAZETTEやる方と一緒にやってほしいです

**Comment by yynhr** [comment]
実装終わり

**Comment by yynhr** [comment]
駅名のGAZETTEはこれ見てやってみてください
https://sap-dbs-japan.slack.com/archives/CBV4GT8D7/p1539875047000100

**Comment by hemipogo** [comment]
改行コードをlfだけにすればCSVアップロードできるかも？
