### ISSUE TITLE
平日／休日の選択させる

### ISSUE THREAD

**Issue by hemipogo** [odpt2018/sapj-opd-trainschedulebot-recast#9]
BOT「乗りたい曜日はいつですか？
1. 平日
2. 土休日」

あなた「1」

というテキストのやり取りだけで平日という条件をNode側に送れるようにする。

**Comment by Miwako1127** [comment]
これって、数字の１とか２をentityとして登録するイメージでしょうか？実装イメージがわかなくて困っています。
いっそのこと、最後の質問に持ってきて、ボタン選択式にした方が良いかなと思うのですが、どうでしょう？

**Comment by yynhr** [comment]
ボタンじゃないと実装難しそうですね。ひとまずボタンにしてみますか？

**Comment by Miwako1127** [comment]
ボタンにしても、１とか２で渡すのは無理そうです。
よねちゃんと木村さんにも一緒に数時間頑張ってもらったのに、できませんでした…。
Nodeで頑張っていただければと思います。

**Comment by hemipogo** [comment]
ヤマト方式難しそうなので、ボタンで選択式にしていただければと思います＞＜
渡すワードは、「平日」「休日」の2択でお願いいたします。

**Comment by Miwako1127** [comment]
train-timetable-bot-originalに追加しておきました！
